kotlin.code.style=official
kotlin.stdlib.default.dependency=false

projectName=HQBukkitTemplate
projectGroup=kr.skh6075.hforestmc
projectVersion=1.0.0-SNAPSHOT
projectAuthors=HQService,skh6075
projectUrl=https://github.com/hforest-mc/

kotlinVersion=2.3.0
spigotVersion=1.21.4-R0.1-SNAPSHOT
shadowVersion=9.3.0
hqFrameworkVersion=2.1.0-SNAPSHOT
